services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 127.0.0.1:10000:10000
    command: "azurite-blob --blobHost 0.0.0.0"
    volumes:
      - /home/yfozekosh/azurite:/data

  funcs:
    build: .
    ports:
      - "8080:80"
    environment:
      - AzureWebJobsStorage="UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite:10000/"
    depends_on:
      - azurite
